doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '14'
        types:
            property_id: 'App\Catalog\Shared\Infrastructure\Persistence\Doctrine\Property\PropertyIdType'
            property_title: 'App\Catalog\Shared\Infrastructure\Persistence\Doctrine\Property\PropertyTitleType'
            property_description: 'App\Catalog\Shared\Infrastructure\Persistence\Doctrine\Property\PropertyDescriptionType'
            property_common_characteristics: 'App\Catalog\Shared\Infrastructure\Persistence\Doctrine\Property\PropertyCommonCharacteristicsType'
            property_location: 'App\Catalog\Shared\Infrastructure\Persistence\Doctrine\Property\PropertyLocationType'
            property_gallery: 'App\Catalog\Shared\Infrastructure\Persistence\Doctrine\Property\PropertyGalleryType'
            
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            RentalProperty:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Catalog/RentalProperty/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Catalog\RentalProperty\Domain'
                alias: RentalProperty
            SharedProperty:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Catalog/Shared/Infrastructure/Persistence/Doctrine/Property'
                prefix: 'App\Catalog\Shared\Domain\Property'
                alias: SharedProperty
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
