version: '3.5'

services:
  housing-web:
    container_name: housing-web
    build:
      context: ./docker/nginx
      args:
        UID: 1000
    ports:
      - 1000:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - housing-app
    networks:
      - housing-network

  housing-app:
    container_name: housing-app
    build:
      context: docker/php
      args:
        UID: 1000
    volumes:
      - ./:/appdata/www
    networks:
      - housing-network

  housing-db:
    container_name: housing-db
    build:
      context: ./docker/database
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    ports:
      - ${POSTGRES_PORT_EXPOSED}:${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - housing-network

volumes:
  db-data:

networks:
  housing-network: