# controllers:
#     resource: ../src/Controller
#     type: attribute

api.rental-property.create:
  path: /api/rental-property
  controller: App\Action\RentalProperty\RentalPropertyCreateController
  methods: [ POST ]

api.rental-property.find:
  path: /api/rental-property/{id}
  controller: App\Action\RentalProperty\RentalPropertyFindController
  methods: [ GET ]