# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    
    _instanceof:
        App\Shared\Domain\Bus\Command\CommandHandler:
            tags: ['internal.command_handler']

        App\Shared\Domain\Bus\Query\QueryHandler:
            tags: ['internal.query_handler']
        
        App\Shared\Domain\Bus\Event\DomainEventSubscriber:
            tags: ['internal.event_subscriber']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Shared/Infrastructure/Persistence/Doctrine/Migrations'
    
    App\Api\:
        resource: '../src/Api'
        tags: ['controller.service_arguments']


    App\Shared\Domain\Event\KernelException:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }


    ### Buses
    App\Shared\Domain\Bus\Command\CommandBus:
        class: App\Shared\Infrastructure\Bus\Command\InMemoryCommandBus
        arguments: [ !tagged internal.command_handler ]

    App\Shared\Domain\Bus\Query\QueryBus:
        class: App\Shared\Infrastructure\Bus\Query\InMemoryQueryBus
        arguments: [ !tagged internal.query_handler ]
    
    # App\Shared\Domain\Bus\Event\EventBus:
    #     class: App\Shared\Infrastructure\Bus\Event\InMemoryEventBus
    #     arguments: [ !tagged internal.event_subscriber ]


    App\Shared\Domain\Bus\Event\EventBus: '@App\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqEventBus'

    App\Shared\Infrastructure\Bus\Event\RabbitMq\RabbitMqConnection:
        arguments:
            $host: '%env(RABBITMQ_HOST)%'
            $port: '%env(RABBITMQ_PORT)%'
            $user: '%env(RABBITMQ_USER)%'
            $password: '%env(RABBITMQ_PASSWORD)%'


    App\Shared\Infrastructure\Bus\Event\DomainEventMapping:
        arguments: [!tagged internal.event_subscriber]
        
    App\Shared\Infrastructure\Bus\Event\DomainEventSubscriberLocator:
        arguments: [!tagged internal.event_subscriber]


